language: php
dist: xenial

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer install --no-interaction --prefer-dist

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
