language: php
dist: bionic
os: linux

php:
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly


before_install:
  # Disable xdebug since its buggy on travis.
  - phpenv config-rm xdebug.ini || echo "xdebug not available"

jobs:
  allow_failures:
    - php: 7.4snapshot
    - php: nightly

# Make sure all dev dependencies are installed, ignore platform requirements because Travis is missing the xdebug on some images
before_script:
  - composer install --no-interaction --prefer-dist --ignore-platform-reqs

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
